# Uncomment the next line to define a global platform for your project
platform :ios, '12.0'

target 'ShopAppViper' do
  use_frameworks!
  
  pod 'Cosmos', '~> 23.0'
 
  
  
  
  # Disable signing for pods
  post_install do |installer|
    installer.generated_projects.each do |project|
      project.targets.each do |target|
          target.build_configurations.each do |config|
              config.build_settings['CODE_SIGNING_ALLOWED'] = 'NO'
              config.build_settings.delete 'IPHONEOS_DEPLOYMENT_TARGET'
           end
      end
    end
  end

end
